export const CREATE_USER_SESSION_SUCCESS = "CREATE_USER_SESSION_SUCCESS";
export const CREATE_USER_SESSION_ERROR = "CREATE_USER_SESSION_ERROR";
export const CREATE_USER_SESSION_REQUEST = "CREATE_USER_SESSION_REQUEST";