export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const FETCH_VARIATIONS_START = 'FETCH_VARIATIONS_START';
export const FETCH_VARIATIONS_SUCCESS = 'FETCH_VARIATIONS_SUCCESS';
export const FETCH_VARIATIONS_FAILURE = 'FETCH_VARIATIONS_FAILURE';

export const FETCH_PRODUCT_START = 'FETCH_PRODUCT_START';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';

export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const SET_CART_INFO = 'SET_CART_INFO';
export const ADD_TO_CART = 'ADD_TO_CART';
export const SET_USER = 'SET_USER';

export const USER_LOGIN_START = 'USER_LOGIN_START';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTRATION_START = 'USER_REGISTRATION_START';
export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
export const USER_REGISTRATION_FAILURE = 'USER_REGISTRATION_FAILURE';

export const REMOVE_CART_PRODUCT_START = 'REMOVE_CART_PRODUCT_START';
export const REMOVE_CART_PRODUCT_SUCCESS = 'REMOVE_CART_PRODUCT_SUCCESS';
export const REMOVE_CART_PRODUCT_FAILURE = 'REMOVE_CART_PRODUCT_FAILURE';

export const DECREASE_CART_PRODUCT_QTY_START = 'DECREASE_CART_PRODUCT_QTY_START';
export const DECREASE_CART_PRODUCT_QTY_SUCCESS = 'DECREASE_CART_PRODUCT_QTY_SUCCESS';
export const DECREASE_CART_PRODUCT_QTY_FAILURE = 'DECREASE_CART_PRODUCT_QTY_FAILURE';

export const INCREASE_CART_PRODUCT_QTY_START = 'INCREASE_CART_PRODUCT_QTY_START';
export const INCREASE_CART_PRODUCT_QTY_SUCCESS = 'INCREASE_CART_PRODUCT_QTY_SUCCESS';
export const INCREASE_CART_PRODUCT_QTY_FAILURE = 'INCREASE_CART_PRODUCT_QTY_FAILURE';

export const FETCH_CART_START = 'FETCH_CART_START';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';
export const FETCH_CART_FAILURE = 'FETCH_CART_FAILURE';

export const RESET_CART = 'RESET_CART';

export const ADD_TO_CART_START = 'ADD_TO_CART_START';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';
