export const GET_PRODUCT_BY_ID_REQUEST = 'GET_PRODUCT_BY_ID_REQUEST';
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS';
export const GET_PRODUCT_BY_ID_ERROR = 'GET_PRODUCT_BY_ID_ERROR';
export const GET_PRODUCT_BY_ID_RESET = 'GET_PRODUCT_BY_ID_RESET';
export const DISMISS_GET_PRODUCT_BY_ID_ERROR = 'DISMISS_GET_PRODUCT_BY_ID_ERROR';