version: '3'

services:
  server:
    build:
      context: $GOPATH/src/github.com/anabiozz/lapkin-project/lapkins
      dockerfile: Dockerfile
    image: "lapkins:latest"
    container_name: lapkins
    ports:
      - "8080:8080"
  api:
    build: 
      context: $GOPATH/src/github.com/anabiozz/lapkin-project/lapkin-api
      dockerfile: Dockerfile
    image: "lapkins-api:latest"
    container_name: lapkins-api
    ports:
      - "8081:8081"