export const GET_VARIANT_REQUEST = 'GET_VARIANT_REQUEST';
export const GET_VARIANT_SUCCESS = 'GET_VARIANT_SUCCESS';
export const GET_VARIANT_ERROR = 'GET_VARIANT_ERROR';
export const GET_VARIANT_RESET = 'GET_VARIANT_RESET';
export const DISMISS_GET_VARIANT_ERROR = 'DISMISS_GET_VARIANT_ERROR';