export const GET_VARIATION_REQUEST = 'GET_VARIATION_REQUEST';
export const GET_VARIATION_SUCCESS = 'GET_VARIATION_SUCCESS';
export const GET_VARIATION_ERROR = 'GET_VARIATION_ERROR';
export const GET_VARIATION_RESET = 'GET_VARIATION_RESET';
export const DISMISS_GET_VARIATION_ERROR = 'DISMISS_GET_VARIATION_ERROR';