export const DISMISS_GET_CATEGORIES_ERROR = "DISMISS_GET_CATEGORIES_ERROR";
export const GET_CATEGORIES_ERROR = "GET_CATEGORIES_ERROR";
export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_RESET = "GET_CATEGORIES_RESET";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";