export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';
export const ADD_PRODUCT_RESET = 'ADD_PRODUCT_RESET';

export const INCREASE_PRODUCT_QUANTITY_REQUEST = 'INCREASE_PRODUCT_QUANTITY_REQUEST';
export const INCREASE_PRODUCT_QUANTITY_SUCCESS = 'INCREASE_PRODUCT_QUANTITY_SUCCESS';
export const INCREASE_PRODUCT_QUANTITY_ERROR = 'INCREASE_PRODUCT_QUANTITY_ERROR';

export const DECREASE_PRODUCT_QUANTITY_REQUEST = 'DECREASE_PRODUCT_QUANTITY_REQUEST';
export const DECREASE_PRODUCT_QUANTITY_SUCCESS = 'DECREASE_PRODUCT_QUANTITY_SUCCESS';
export const DECREASE_PRODUCT_QUANTITY_ERROR = 'DECREASE_PRODUCT_QUANTITY_ERROR';

export const REMOVE_PRODUCT_REQUEST = 'REMOVE_PRODUCT_REQUEST';
export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS';
export const REMOVE_PRODUCT_ERROR = 'REMOVE_PRODUCT_ERROR';

export const LOAD_CART_REQUEST = 'LOAD_CART_REQUEST';
export const LOAD_CART_SUCCESS = 'LOAD_CART_SUCCESS';
export const LOAD_CART_ERROR = 'LOAD_CART_ERROR';
export const LOAD_CART_RESET = 'LOAD_CART_RESET';

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR';
export const CREATE_ORDER_RESET = 'CREATE_ORDER_RESET';

export const DISMISS_ADD_PRODUCT_TO_CART_ERROR = 'DISMISS_ADD_PRODUCT_TO_CART_ERROR';
export const DECREASE_CART_ITEM = 'DECREASE_CART_ITEM';
