export const ADD_ITEM_TO_CART_REQUEST = 'ADD_ITEM_TO_CART_REQUEST';
export const ADD_ITEM_TO_CART_SUCCESS = 'ADD_ITEM_TO_CART_SUCCESS';
export const ADD_ITEM_TO_CART_ERROR = 'ADD_ITEM_TO_CART_ERROR';
export const ADD_ITEM_TO_CART_RESET = 'ADD_ITEM_TO_CART_RESET';

export const INCREASE_CART_ITEM_REQUEST = 'INCREASE_CART_ITEM_REQUEST';
export const INCREASE_CART_ITEM_SUCCESS = 'INCREASE_CART_ITEM_SUCCESS';
export const INCREASE_CART_ITEM_ERROR = 'INCREASE_CART_ITEM_ERROR';

export const CREATE_CART_SESSION_REQUEST = 'CREATE_CART_SESSION_REQUEST';
export const CREATE_CART_SESSION_SUCCESS = 'CREATE_CART_SESSION_SUCCESS';
export const CREATE_CART_SESSION_ERROR = 'CREATE_CART_SESSION_ERROR';

export const DISMISS_ADD_PRODUCT_TO_CART_ERROR = 'DISMISS_ADD_PRODUCT_TO_CART_ERROR';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const LOAD_CART = 'LOAD_CART';
export const DECREASE_CART_ITEM = 'DECREASE_CART_ITEM';
