export const variations = [
  {
    id: 1,
    productId: 1,
    sku: 1,
    name: 'wood-framed-posters',
    default: true,
    attributes: [
      {name: 'Размер', value: '300x400'},
      {name: 'Рамка', value: 'Деревянная'},
    ],
    price: '50',
    thumbnail: 'https://picsum.photos/id/1/200/300',
    images: [{src: 'https://picsum.photos/id/1/200/300'},{src: 'https://picsum.photos/id/5/200/300'}],
  },
  {
    id: 2,
    productId: 1,
    sku: 2,
    name: 'wood-framed-posters',
    default: false,
    attributes: [
      {name: 'Размер', value: '500x600'},
      {name: 'Рамка', value: 'Деревянная'},
    ],
    price: '80',
    thumbnail: 'https://picsum.photos/id/2/200/300',
    images: [{src: 'https://picsum.photos/id/2/200/300'},{src: 'https://picsum.photos/id/6/200/300'}],
  },
  {
    id: 3,
    productId: 1,
    sku: 3,
    name: 'posters',
    default: true,
    attributes: [
      {name: 'Размер', value: '300x400'},
      {name: 'Рамка', value: 'Без рамки'},
    ],
    price: '57',
    thumbnail: 'https://picsum.photos/id/3/200/300',
    images: [{src: 'https://picsum.photos/id/3/200/300'},{src: 'https://picsum.photos/id/7/200/300'}],
  },
  {
    id: 4,
    productId: 1,
    sku: 4,
    default: false,
    name: 'posters',
    attributes: [
      {name: 'Размер', value: '500x600'},
      {name: 'Рамка', value: 'Без рамки'},
    ],
    price: '79',
    thumbnail: 'https://picsum.photos/id/4/200/300',
    images: [{src: 'https://picsum.photos/id/4/200/300'},{src: 'https://picsum.photos/id/8/200/300'}],
  },
  {
    id: 5,
    productId: 7,
    sku: 5,
    name: 'lamps',
    default: true,
    attributes: [
      {name: 'Цвет', value: 'Белый'},
    ],
    price: '700',
    thumbnail: 'https://picsum.photos/id/5/200/300',
    images: [{src: 'https://picsum.photos/id/9/200/300'},{src: 'https://picsum.photos/id/10/200/300'}],
  },
  {
    id: 6,
    productId: 5,
    sku: 6,
    default: true,
    name: 'postcards',
    attributes: [
      {name: 'Размер', value: '50x60'},
    ],
    price: '20',
    thumbnail: 'https://picsum.photos/id/6/200/300',
    images: [{src: 'https://picsum.photos/id/11/200/300'},{src: 'https://picsum.photos/id/12/200/300'}],
  },
];
